export type ProjectStateErrorCode =
  | "PROJECT_STATE_ADMIN_ACCESS_DENIED"
  | "PROJECT_PUBLIC_CONTACT_ACCESS_DENIED"
  | "PROJECT_PUBLIC_CONTACT_NOT_FOUND"
  | "PROJECT_PUBLIC_CONTACT_REFERENCE_INVALID"
  | "PROJECT_PUBLIC_CONTACT_STALE"
  | "PROJECT_EDITORIAL_NOT_FOUND"
  | "PROJECT_EDITORIAL_REFERENCE_INVALID"
  | "PROJECT_EDITORIAL_STALE"
  | "PROJECT_EDITORIAL_MEDIA_ORDER_LOCKED"
  | "PROJECT_EDITORIAL_MEDIA_ORDER_INVALID"
  | "PROJECT_EDITORIAL_JOB_ACCESS_DENIED"
  | "PROJECT_URL_REFERENCE_INVALID"
  | "PROJECT_URL_POLICY_REQUIRED"
  | "PROJECT_URL_POLICY_IN_USE"
  | "PROJECT_URL_ENTRY_NOT_FOUND"
  | "PROJECT_URL_STALE"
  | "PROJECT_URL_PATH_RESERVED"
  | "PROJECT_URL_PATH_CONFLICT"
  | "PROJECT_URL_REDIRECT_TARGET_INVALID";

export class ProjectStateError extends Error {
  constructor(readonly code: ProjectStateErrorCode) {
    super(code);
    this.name = "ProjectStateError";
  }
}
