export type ProjectStateErrorCode =
  | "PROJECT_STATE_ADMIN_ACCESS_DENIED"
  | "PROJECT_PUBLIC_CONTACT_ACCESS_DENIED"
  | "PROJECT_PUBLIC_CONTACT_NOT_FOUND"
  | "PROJECT_PUBLIC_CONTACT_REFERENCE_INVALID"
  | "PROJECT_PUBLIC_CONTACT_STALE"
  | "PROJECT_EDITORIAL_NOT_FOUND"
  | "PROJECT_EDITORIAL_REFERENCE_INVALID"
  | "PROJECT_EDITORIAL_STALE"
  | "PROJECT_EDITORIAL_MEDIA_ORDER_LOCKED"
  | "PROJECT_EDITORIAL_MEDIA_ORDER_INVALID"
  | "PROJECT_EDITORIAL_JOB_ACCESS_DENIED";

export class ProjectStateError extends Error {
  constructor(readonly code: ProjectStateErrorCode) {
    super(code);
    this.name = "ProjectStateError";
  }
}
