import Link from "next/link";
import { LoginDialog } from "../../modules/identity-access/client.ts";
import { LeadRequestDialog } from "./LeadRequestDialog.tsx";
import { SiteFooter } from "./SiteFooter.tsx";
import styles from "./StartLanding.module.css";

function PublicHeader({ loginRequested }: { loginRequested: boolean }) {
  return <header className="mx-auto flex w-full max-w-[1360px] items-center justify-between px-5 py-5 sm:px-6 lg:py-7"><Link href="/" className="inline-flex min-h-11 items-center gap-3 text-[var(--ch-white)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ch-accent)] focus-visible:ring-offset-4 focus-visible:ring-offset-[var(--ch-bg-deepest)]" aria-label="AMS Data Hub - главная"><span className="grid size-10 place-items-center border border-[var(--ch-border-hover)] bg-[var(--ch-surface-subtle)] text-[11px] font-extrabold">АМС</span><span className="text-sm font-extrabold">СТАРТ</span></Link><LoginDialog initialOpen={loginRequested} /></header>;
}

function HeroCopy() {
  return <div className="relative z-10 max-w-3xl"><p className="mb-6 text-[11px] font-bold uppercase text-[var(--ch-accent)]">Стартовая база для веб-приложений</p><h1 className="max-w-[850px] text-[clamp(44px,6.2vw,84px)] font-extrabold leading-[0.98] text-[var(--ch-white)]">AMS Data Hub</h1><p className="mt-7 max-w-2xl text-[clamp(17px,1.45vw,21px)] leading-[1.62] text-[var(--ch-soft-white)]">Нейтральный foundation для кабинетов, CRM, аналитики и внутренних систем: вход, роли, организации, админка, очередь задач и готовый публичный слой.</p><div className="mt-9 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><LeadRequestDialog /><p className="max-w-[285px] text-xs leading-5 text-[var(--ch-muted-ondark)]">Шаблон можно взять как основу и быстро заменить доменную модель под новый продукт.</p></div><div className="mt-14 flex flex-wrap gap-x-7 gap-y-3 border-t border-[var(--ch-border-subtle)] pt-5 text-xs font-semibold uppercase text-[var(--ch-copy-ondark)]"><span>CRM</span><span>Аналитика</span><span>Внутренние кабинеты</span></div></div>;
}

function HeroVisual() {
  return <div className="relative min-h-[420px] lg:min-h-[620px]" aria-hidden><div className={`${styles.visual} absolute inset-0 overflow-hidden border border-[var(--ch-border-subtle)] bg-[var(--ch-bg-deeper)]/55`}><div className="absolute inset-0 bg-[image:var(--ch-hero-gradient)]" /><svg className="absolute inset-0 h-full w-full" viewBox="0 0 560 680" fill="none"><path d="M-20 586C115 498 178 529 268 403C351 288 406 184 596 106" stroke="var(--ch-data-line)" strokeWidth="2" /><path d="M-15 620C138 535 201 552 302 427C389 319 428 215 602 148" stroke="var(--ch-data-line-faint)" strokeWidth="1" /><path d="M30 552L138 478L219 503L316 353L419 302L532 162" stroke="var(--ch-data-line-soft)" strokeWidth="1" /><circle cx="138" cy="478" r="5" fill="var(--ch-accent)" /><circle cx="219" cy="503" r="4" fill="var(--ch-soft-white)" /><circle cx="316" cy="353" r="6" fill="var(--ch-accent)" /><circle cx="419" cy="302" r="4" fill="var(--ch-soft-white)" /><circle cx="532" cy="162" r="7" fill="var(--ch-accent)" /></svg><div className="absolute left-6 top-6 border border-[var(--ch-border-subtle)] bg-[var(--ch-bg-deepest)]/75 px-4 py-3 backdrop-blur-sm sm:left-8 sm:top-8"><p className="text-[10px] font-bold uppercase text-[var(--ch-subtle-ondark)]">Готовность</p><p className="mt-1 text-2xl font-bold text-[var(--ch-white)]">core v1</p></div><div className="absolute bottom-7 right-6 w-[min(280px,calc(100%_-_48px))] border border-[var(--ch-border-subtle)] bg-[var(--ch-bg-dark)]/88 p-5 backdrop-blur-md sm:bottom-9 sm:right-8"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase text-[var(--ch-subtle-ondark)]">Модули</p><p className="mt-2 text-lg font-bold text-[var(--ch-white)]">Кабинет и админка</p></div><span className="size-2 bg-[var(--ch-accent)] shadow-[var(--ch-signal-ring)]" /></div><div className="mt-5 grid grid-cols-5 items-end gap-2">{[26, 36, 48, 68, 92].map((height, index) => <span key={height} className="block bg-[var(--ch-accent)]/75" style={{ height, opacity: 0.45 + index * 0.12 }} />)}</div></div></div></div>;
}

export function StartLanding({ loginRequested }: { loginRequested: boolean }) {
  return <main className="theme-public start-landing min-h-screen overflow-hidden bg-[var(--ch-bg-deepest)] text-[var(--ch-white)]"><section className="relative isolate min-h-screen"><div className={`${styles.grid} absolute inset-0 -z-20`} aria-hidden /><div className={`${styles.atmosphere} absolute inset-0 -z-10`} aria-hidden /><PublicHeader loginRequested={loginRequested} /><div className="mx-auto grid w-full max-w-[1360px] gap-12 px-5 pb-12 pt-14 sm:px-6 sm:pt-20 lg:min-h-[calc(100vh-96px)] lg:grid-cols-[minmax(0,7fr)_minmax(360px,5fr)] lg:items-center lg:gap-16 lg:pb-20 lg:pt-10"><HeroCopy /><HeroVisual /></div></section><SiteFooter /></main>;
}
