export const TENANT_OWNED_MODELS = [
  "Organization",
  "Member",
  "Project",
  "ProjectMember",
  "Notification",
  "NotificationRead",
  "AuditEvent",
  "IdempotencyKey",
  "OutboxEvent",
  "JobRun",
  "PublicUrlIdReservation",
  "MediaAsset",
  "MediaSource",
  "ProjectCatalogSubscription",
  "ProjectCatalogSubscriptionCity",
  "ProjectCatalogSubscriptionSelection",
  "ProjectPublicContact",
  "EntityEditorial",
  "EntityMediaOrderPolicy",
  "ProjectUrlPolicy",
  "ProjectUrlEntry",
  "ProjectRedirect",
  "ProjectUrlTombstone",
  "Source",
  "SourceCredentialRef",
  "SourceManualRunRequest",
  "OperationalActionRequest",
  "SourceSafetyPolicy",
  "SourceRevision",
  "SourceRevisionRecord",
  "RawArtifactPutAttempt",
  "RawArtifactDeletion",
  "ListingDevelopmentLink",
  "Agent",
  "ListingAgentBinding",
  "AgentExternalIdentity",
  "AgentSourceEvidence",
  "AgentMatchReview",
  "AgentMergeEvent",
  "AgentConsentBatch",
  "ProjectCurrentSnapshotManifest",
  "ProjectSnapshotSequence",
  "SnapshotBuildInput",
  "SnapshotBuildInputPart",
  "SnapshotPublicationBinding",
  "SnapshotArtifactStageReceipt",
  "SnapshotRollbackReservation",
  "SnapshotRollbackBinding",
  "DeliveryRun",
  "ProjectAckCredential",
  "SnapshotAckRotationReceipt",
  "SourceManualApprovalReceipt",
  "SourceManualApprovalMutation",
  "InventoryIdentity",
  "InventoryLifecycleEvent",
  "DevelopmentExternalIdentity",
  "PriceObservation",
  "SharedMediaAsset",
] as const;

export type TenantOwnedModel = (typeof TENANT_OWNED_MODELS)[number];

export function isTenantOwnedModel(model: string): model is TenantOwnedModel {
  return TENANT_OWNED_MODELS.some((candidate) => candidate === model);
}
